# NumPy

## Arrays and matrices

Numpy full form "Numerical Python"
Travis Oliphant created NumPy package in 2005 by injecting the features of the ancestor module Numeric into another module Numarray.
NumPy is a fundamental package for scientific computing in Python.It is a Python library that provide a multidimensional array object,various derived objects(such as masked array and matrices) and an assorted of routines for fast operations on array,including mnathematical , logical ,shape manipulation , sorting , selecting , I/O , discrete Fourier transforms , basic linear algebra , basic statistical operations , random simulation and much more....

In [1]:
import numpy as np

## Creating Arrays

In [7]:
# creating a nd array
# every elements must be of same data type(conversion can be possible)
data1 = [1,2,3,4,5]  #list
arr1 = np.array(data1)
print(data1 , type(data1))
print(arr1 , type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
data1 = [1,2.2,3,4,5]  #list
arr1 = np.array(data1)
print(data1 , type(data1))
print(arr1 , type(arr1))

[1, 2.2, 3, 4, 5] <class 'list'>
[1.  2.2 3.  4.  5. ] <class 'numpy.ndarray'>


In [9]:
data2 = [range(1,5) ,range(5,9)] # list of lists
print(data2 , type(data2))
arr2 = np.array(data2)
print(arr2 , type(arr2))

[range(1, 5), range(5, 9)] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [11]:
list2 = arr2.tolist()

In [12]:
print(list2 , type(list2))

[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
