### ReShaping

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])
arr.resize(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
f = arr.flatten()

In [4]:
f

array([1, 2, 3, 4, 5, 6])

In [5]:
arr = np.array([1,2,3,4,5,6])
# applying numpy.__lt__() method
print(arr.__lt__(4))
print(arr.__gt__(3))

[ True  True  True False False False]
[False False False  True  True  True]


In [6]:
arr1 = np.array([1,-2,3,4,5,6])
print(arr1.__neg__())

[-1  2 -3 -4 -5 -6]


In [7]:
print(np.clip(arr,0,3))

[1 2 3 3 3 3]


In [8]:
print(np.clip(arr,0,4))

[1 2 3 4 4 4]


In [9]:
# arrange is like a range , except it returns an array (but not a list)
int_list = list(range(5))
print(int_list , type(int_list[0]), type(int_list))

int_array=np.arange(5)
print(int_array , int_array.dtype,type(int_array))

float_array = int_array.astype(float)
print(float_array , float_array.dtype , type(float_array))

[0, 1, 2, 3, 4] <class 'int'> <class 'list'>
[0 1 2 3 4] int64 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] float64 <class 'numpy.ndarray'>


In [10]:
matrix = np.arange(10,dtype = float)
print(matrix , matrix.dtype , type(matrix) , matrix.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64 <class 'numpy.ndarray'> (10,)


In [11]:
matrix = matrix.reshape(2,5)
print(matrix , matrix.dtype , type(matrix) , matrix.shape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)


In [12]:
# To create an identity matrix
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
b = np.eye(3)  # identity matrix
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Tuple to ndarray
tuple1 = (1,2,3,4)
ar = np.asarray(tuple1)
print(ar)

[1 2 3 4]


In [15]:
# To change the types
mx_ls = np.ones((3,4),dtype = int)
print(mx_ls)
mx_ls = np.ones((3,4),dtype = bool)
print(mx_ls)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### Selection

In [16]:
data1 = [1,2,3,4,5]
arr1 = np.array(data1)
print(arr1 , type(arr1) , arr1.dtype , arr1.shape)
print(arr1[0],arr1[-5])

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
1 1


In [17]:
print(arr1[4],arr1[-1])
print(arr1[2:],arr1[:3])

5 5
[3 4 5] [1 2 3]


In [18]:
import math
print(math.gcd(100,750))

# using numpy
print(np.gcd(100,750))

50
50


In [19]:
# Finding LCM
print(math.lcm(100,200))

200


In [20]:
arr = np.array([3,6,9])
x = np.lcm.reduce(arr)
print(x)

18


## Views and Copies

In [21]:
arr = np.arange(10)
print(arr , type(arr),arr.dtype , arr.shape)
print(arr[5:8])
arr[5:8] = 12
print(arr)
arr_view = arr[5:8]   # creates a view of arr , not a copy
print(arr_view , type(arr_view) , arr_view.dtype , arr_view.shape)
print()

arr_view[:] = 13
print(arr_view)
print(arr)
print()

arr_copy = arr[5:8].copy()  # create a copy of array
print(arr_copy , type(arr_copy) , arr_copy.dtype,arr_copy.shape)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int64 (10,)
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12] <class 'numpy.ndarray'> int64 (3,)

[13 13 13]
[ 0  1  2  3  4 13 13 13  8  9]

[13 13 13] <class 'numpy.ndarray'> int64 (3,)


In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr>5)
print(arr[arr>5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]


In [23]:
print(arr % 2 == 0)
print(arr[arr%2 ==0])

[False  True False  True False  True False  True False]
[2 4 6 8]


In [24]:
names = np.array(['Sree','Asad','Ritu','Rituraj','sana','arijit','anwesha','sneha'])
print(names)

['Sree' 'Asad' 'Ritu' 'Rituraj' 'sana' 'arijit' 'anwesha' 'sneha']


In [25]:
print(names == 'Asad')

[False  True False False False False False False]


In [26]:
print(names[names == 'Asad'])
print(names[names != 'Asad'])
print(names[(names == 'Asad')| (names == 'sana')])
names[names != 'Asad'] = 'sana'
print(names)
print(np.unique(names))

['Asad']
['Sree' 'Ritu' 'Rituraj' 'sana' 'arijit' 'anwesha' 'sneha']
['Asad' 'sana']
['sana' 'Asad' 'sana' 'sana' 'sana' 'sana' 'sana' 'sana']
['Asad' 'sana']


## Vectorized Operations

In [27]:
nums = np.arange(5)
print(nums)
print(nums * 5)
nums = np.sqrt(nums)
print(nums)
print(np.ceil(nums))
print(np.floor(nums))
print(np.isnan(nums))

[0 1 2 3 4]
[ 0  5 10 15 20]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 2. 2.]
[0. 1. 1. 1. 2.]
[False False False False False]


### numpy.dot() function

In [28]:
a = np.array([[100,200],[23,12]])
b = np.array([[10,20],[12,21]])

dot = np.dot(a,b)
print(dot)

[[3400 6200]
 [ 374  712]]


In [34]:
ver1 = np.random.randn(10)
print(ver1)

ver2 = np.random.randn(10)
print(ver2)

dist = np.sqrt(np.sum((ver1 - ver2)**2))
print(dist)

[ 1.59018569 -0.1260271  -0.4468118  -1.26141814 -0.3509739  -0.2239029
 -0.0345435   1.13591768 -0.99444011 -0.36414356]
[ 1.72329893  0.68876276  0.21507772 -1.57929114 -0.30928779 -0.67548817
 -0.5561112   1.027307   -1.11307796 -1.76873451]
1.9228076928607296
